// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMrUxcelfieWbelFOrupuxHkoe0c6vaIg',
    appId: '1:903444119343:web:27b0a663c8d63e9e52abda',
    messagingSenderId: '903444119343',
    projectId: 'adotapets-dd47c',
    authDomain: 'adotapets-dd47c.firebaseapp.com',
    storageBucket: 'adotapets-dd47c.firebasestorage.app',
    measurementId: 'G-Y24T7QWFCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvW7UY4NlbtzygKbvmzo3q0mH0tWQArPk',
    appId: '1:903444119343:android:d6c10e63d2c8303b52abda',
    messagingSenderId: '903444119343',
    projectId: 'adotapets-dd47c',
    storageBucket: 'adotapets-dd47c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXKx5mi-BlWNSw5eqAHuvPmSKEOYZ84S0',
    appId: '1:903444119343:ios:43e345542ffdd1ce52abda',
    messagingSenderId: '903444119343',
    projectId: 'adotapets-dd47c',
    storageBucket: 'adotapets-dd47c.firebasestorage.app',
    iosBundleId: 'com.example.adotaPetsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXKx5mi-BlWNSw5eqAHuvPmSKEOYZ84S0',
    appId: '1:903444119343:ios:43e345542ffdd1ce52abda',
    messagingSenderId: '903444119343',
    projectId: 'adotapets-dd47c',
    storageBucket: 'adotapets-dd47c.firebasestorage.app',
    iosBundleId: 'com.example.adotaPetsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMrUxcelfieWbelFOrupuxHkoe0c6vaIg',
    appId: '1:903444119343:web:8d4524a12f4d47e152abda',
    messagingSenderId: '903444119343',
    projectId: 'adotapets-dd47c',
    authDomain: 'adotapets-dd47c.firebaseapp.com',
    storageBucket: 'adotapets-dd47c.firebasestorage.app',
    measurementId: 'G-2LZHP1LTEX',
  );
}
